<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>noescape</RootNamespace>
    <AssemblyName>horseman</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\creepy_wallpaper.bmp" LogicalName="horseman.Resources.creepy_wallpaper.bmp" />
    <EmbeddedResource Include="Resources\thingy.exe" LogicalName="horseman.Resources.thingy.exe" />
    <EmbeddedResource Include="Resources\guest.bmp" LogicalName="horseman.Resources.guest.bmp" />
    <EmbeddedResource Include="Resources\guest.png" LogicalName="horseman.Resources.guest.png" />
    <EmbeddedResource Include="Resources\user.bmp" LogicalName="horseman.Resources.user.bmp" />
    <EmbeddedResource Include="Resources\user.png" LogicalName="horseman.Resources.user.png" />
    <EmbeddedResource Include="Resources\user-32.png" LogicalName="horseman.Resources.user-32.png" />
    <EmbeddedResource Include="Resources\user-40.png" LogicalName="horseman.Resources.user-40.png" />
    <EmbeddedResource Include="Resources\user-48.png" LogicalName="horseman.Resources.user-48.png" />
    <EmbeddedResource Include="Resources\user-192.png" LogicalName="horseman.Resources.user-192.png" />
  </ItemGroup>
</Project>
